type: "position_controllers/JointGroupPositionController"
joints:
 - left_center_coxa_dynamixel_to_top_coxa_joint
 - left_center_femur_dynamixel_to_left_femur_joint
 - left_center_tibia_dynamixel_to_tibia_joint
