type: "position_controllers/JointGroupPositionController"
joints:
 - right_hind_coxa_dynamixel_to_top_coxa_joint
 - right_hind_femur_dynamixel_to_left_femur_joint
 - right_hind_tibia_dynamixel_to_tibia_joint
