type: "position_controllers/JointGroupPositionController"
joints:
 - right_center_coxa_dynamixel_to_top_coxa_joint
 - right_center_femur_dynamixel_to_left_femur_joint
 - right_center_tibia_dynamixel_to_tibia_joint
